### ISSUE TITLE
FTP Upload Error is still there ...

### ISSUE THREAD

**Issue by DeadP4xel** [olav-st/screencloud-plugins#12]
I always fget this error when i try to upload a screenshot.

![unbenannt](https://cloud.githubusercontent.com/assets/7443226/6226594/fb07ad44-b696-11e4-8022-71e293ab77bc.PNG)

**Comment by hTmlDP** [comment]
As i said, you have to use
ftp=ftplib.FTP()
ftp.connect(host, port)
My fixed version for screencloud is available at http://htmldp.com/screencloud/ftp.zip

**Comment by TheTotenkopf** [comment]
Well thanks for that but ii get still the same error ??

**Comment by hTmlDP** [comment]
Really?
Have you installed it from url? (http://htmldp.com/screencloud/ftp.zip)
It works for me.

**Comment by TheTotenkopf** [comment]
I can do what i want nothing works... Reinstall ScreenCloud. Disable, install and activate the FTP Plugin and always get the Error.

**Comment by hTmlDP** [comment]
Have you installed the plugin from the url i gave you?

**Comment by TheTotenkopf** [comment]
sure i pressed install from URL and Mirror GitHub is that correct ?

**Comment by hTmlDP** [comment]
I don't think so
You have to paste my url in a textbox and wait for the download

**Comment by TheTotenkopf** [comment]
Okey i copied the files from the Zip in /appdata/local/screencloud/plugins and restartet ScreenCloud now it works ... thx for the help !

**Comment by hTmlDP** [comment]
No problem :)
I made this fix for myself some time ago- the older version hadnt been supporting custom FTP ports.
They should fix it, because the ftp plugin is more bugged- as you see, it doesnt work.
I've submitted a fix, they should accept it soon.

**Comment by olav-st** [comment]
I've merged your pull request and it seems to work after some quick testing. Thanks @hTmlDP
