### ISSUE TITLE
Plugin "file" ignores value of "Name" field on saving

### ISSUE THREAD

**Issue by n0guest** [olav-st/screencloud-plugins#23]
Even if you've tried to change name in "Save" dialog, file still will be saved under name received from call of ScreenCloud.formatFilename (main.py:50):

`f = QFile(self.folder + "/" + ScreenCloud.formatFilename(self.nameFormat))`

This behaviour ignores value of argument "name"  in upload function params. I guess, this can be fixed with something like this:

`f = QFile(self.folder + "/" + name)`

I hope, i've explained this issue clear enough.

**Comment by olav-st** [comment]
Fixed by https://github.com/olav-st/screencloud-plugins/commit/5464fa98a3eba227cc194e9c3bda4475fef4c669.
